workflows:
  ios-release:
    name: iOS Release

    environment:
      xcode: latest

    scripts:
      - npm ci
      - npm install -g cordova
      - cordova platform add ios
      - cordova build ios --release

    artifacts:
      - platforms/ios/build/**/*.ipa
      - platforms/ios/build/**/*.xcarchive