name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies
        run: npm install

      - name: Prepare iOS
        run: cordova prepare ios

      - name: Show schemes
        run: xcodebuild -list -workspace "platforms/ios/Экадаши.xcworkspace"

      - name: Build
        run: |
          xcodebuild \
          -workspace "platforms/ios/Экадаши.xcworkspace" \
          -scheme "Экадаши" \
          -configuration Release \
          build